# Generated by Django 3.0.8 on 2021-03-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='projects/')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('locale', models.CharField(max_length=10)),
            ],
        ),
    ]
