# Generated by Django 3.0.8 on 2021-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='locale',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
