# Generated by Django 3.1.3 on 2023-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20230701_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
