# Generated by Django 3.1.3 on 2023-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
