# Generated by Django 3.1.3 on 2023-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_event_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='glow_color_rgba',
            field=models.TextField(blank=True, null=True),
        ),
    ]
