# Generated by Django 3.1.3 on 2023-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_event_glow_color_rgba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
