# Generated by Django 3.1.3 on 2023-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
