# Generated by Django 3.0.8 on 2021-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainaddress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blockchains/'),
        ),
    ]
